// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcess() {
  return window['go']['main']['App']['CancelProcess']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetColumns(arg1) {
  return window['go']['main']['App']['GetColumns'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartProcess(arg1) {
  return window['go']['main']['App']['StartProcess'](arg1);
}
