// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelProcess():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetColumns(arg1:string):Promise<main.ColumnsResult>;

export function GetSettings():Promise<main.Settings>;

export function OpenPath(arg1:string):Promise<void>;

export function PickFile():Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function StartProcess(arg1:main.ProcessOptions):Promise<void>;
